# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        version:
          - '1.19'
          - '1.20'
          - '1.21'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}
    - name: Test
      run: go test -v ./...
  fmt:
    strategy:
      matrix:
        version:
          - '1.19'
          - '1.20'
          - '1.21'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}
    - name: fmt
      run: gofmt -e -d
  vet:
    strategy:
      matrix:
        version:
          - '1.19'
          - '1.20'
          - '1.21'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}
    - name: fmt
      run: go vet ./...
